//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TugDataModel
{
    using System;
    
    public partial class proc_approved_Result2
    {
        public Nullable<int> IDX { get; set; }
        public string InvoiceType { get; set; }
        public string CustomerName { get; set; }
        public string ShipName { get; set; }
        public string JobNo { get; set; }
        public string BillingCode { get; set; }
        public string BillingTemplateTypeLabel { get; set; }
        public string TimeTypeValue { get; set; }
        public string TimeTypeLabel { get; set; }
        public Nullable<double> Amount { get; set; }
        public string Status { get; set; }
        public string Remark { get; set; }
        public string CreateDate { get; set; }
        public string LastUpDate { get; set; }
        public Nullable<int> UserID { get; set; }
    }
}
