//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpecialBillingItem
    {
        public int IDX { get; set; }
        public Nullable<int> SpecialBillingID { get; set; }
        public Nullable<int> OrderServiceID { get; set; }
        public string ServiceDate { get; set; }
        public Nullable<int> ServiceNatureID { get; set; }
        public string ServiceNatureValue { get; set; }
        public string ServiceNature { get; set; }
        public string CustomerShipName { get; set; }
        public Nullable<int> TugNumber { get; set; }
        public Nullable<double> ServiceUnitPrice { get; set; }
        public Nullable<double> FeulUnitPrice { get; set; }
    
        public virtual Billing Billing { get; set; }
    }
}
