//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInfor
    {
        public UserInfor()
        {
            this.UsersRole = new HashSet<UsersRole>();
        }
    
        public int IDX { get; set; }
        public string UserName { get; set; }
        public string Pwd { get; set; }
        public string IsGuest { get; set; }
        public string LanUserName { get; set; }
        public string Lan { get; set; }
        public string Dept { get; set; }
        public string Sec { get; set; }
        public string Name1 { get; set; }
        public string Name2 { get; set; }
        public string WorkNumber { get; set; }
        public string Sex { get; set; }
        public string Tel { get; set; }
        public string Email { get; set; }
        public Nullable<int> OwnerID { get; set; }
        public string CreateDate { get; set; }
        public Nullable<int> AddUserID { get; set; }
        public string LastUpDate { get; set; }
        public string System { get; set; }
        public Nullable<int> Status { get; set; }
        public string LogIP { get; set; }
        public string UserDefinedCol1 { get; set; }
        public string UserDefinedCol2 { get; set; }
        public string UserDefinedCol3 { get; set; }
        public string UserDefinedCol4 { get; set; }
        public Nullable<double> UserDefinedCol5 { get; set; }
        public Nullable<int> UserDefinedCol6 { get; set; }
        public Nullable<int> UserDefinedCol7 { get; set; }
        public Nullable<int> UserDefinedCol8 { get; set; }
        public string UserDefinedCol9 { get; set; }
        public string UserDefinedCol10 { get; set; }
    
        public virtual ICollection<UsersRole> UsersRole { get; set; }
    }
}
