//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_Approve_Billing
    {
        public int IDX { get; set; }
        public Nullable<int> BillingID { get; set; }
        public Nullable<int> Accept { get; set; }
        public string Status { get; set; }
        public Nullable<int> Phase { get; set; }
        public string InvoiceType { get; set; }
        public Nullable<int> PersonID { get; set; }
    }
}
