//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_Arrangement
    {
        public int IDX { get; set; }
        public string WorkDate { get; set; }
        public Nullable<int> TugID { get; set; }
        public Nullable<int> SortNo { get; set; }
        public string TeamName { get; set; }
        public string Name1 { get; set; }
        public string Remark { get; set; }
        public string CreateDate { get; set; }
        public Nullable<int> UserID { get; set; }
        public string LastUpDate { get; set; }
    }
}
