//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_Billing3
    {
        public int IDX { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public string CustomerName { get; set; }
        public Nullable<double> Amount { get; set; }
        public string Status { get; set; }
        public Nullable<int> TimesNo { get; set; }
        public Nullable<int> Phase { get; set; }
        public Nullable<int> OwnerID { get; set; }
        public string CreateDate { get; set; }
        public Nullable<int> UserID { get; set; }
        public string LastUpDate { get; set; }
        public string InvoiceType { get; set; }
        public string Month { get; set; }
        public string BillingCode { get; set; }
        public string Remark { get; set; }
    }
}
