//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_Flow
    {
        public int IDX { get; set; }
        public Nullable<int> BillingID { get; set; }
        public string Task { get; set; }
        public Nullable<int> FlowUserID { get; set; }
        public string StDate { get; set; }
        public string EndDate { get; set; }
        public string UserName { get; set; }
        public string Name1 { get; set; }
        public string Name2 { get; set; }
        public Nullable<int> MarkID { get; set; }
        public Nullable<int> Phase { get; set; }
    }
}
