//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_Inv_BillingItem
    {
        public int IDX { get; set; }
        public Nullable<double> UnitPrice { get; set; }
        public string Currency { get; set; }
        public string TugName { get; set; }
        public string ServiceName { get; set; }
        public string ItemName { get; set; }
        public string ItemCode { get; set; }
        public Nullable<int> SchedulerID { get; set; }
        public Nullable<int> BillingID { get; set; }
        public string ServiceCode { get; set; }
        public string ServiceWorkDate { get; set; }
        public string ServiceWorkTime { get; set; }
        public string DepartBaseTime { get; set; }
        public string ArrivalBaseTime { get; set; }
    }
}
