//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_OrderScheduler
    {
        public Nullable<int> OrderID { get; set; }
        public string HasInvoice { get; set; }
        public string HasInFlow { get; set; }
        public Nullable<int> OrderServiceID { get; set; }
        public string HasBilling { get; set; }
        public string HasBillingInFlow { get; set; }
        public Nullable<int> BillingType { get; set; }
        public Nullable<int> ServiceNatureID { get; set; }
        public string ServiceNatureValue { get; set; }
        public string ServiceNatureLabel { get; set; }
        public string ServiceWorkDate { get; set; }
        public string ServiceWorkTime { get; set; }
        public string EstimatedCompletionTime { get; set; }
        public string ServiceWorkPlace { get; set; }
        public Nullable<int> BigTugNum { get; set; }
        public Nullable<int> MiddleTugNum { get; set; }
        public Nullable<int> SmallTugNum { get; set; }
        public Nullable<int> ServiceJobStateID { get; set; }
        public string ServiceJobStateValue { get; set; }
        public string ServiceJobStateLabel { get; set; }
        public string OrderServiceRemark { get; set; }
        public Nullable<int> ShipID { get; set; }
        public string ShipName { get; set; }
        public Nullable<int> DeadWeight { get; set; }
        public Nullable<int> Length { get; set; }
        public Nullable<int> Width { get; set; }
        public Nullable<int> TEUS { get; set; }
        public string Class { get; set; }
        public int IDX { get; set; }
        public string SchedulerWorkPlace { get; set; }
        public Nullable<int> TugID { get; set; }
        public string TugName1 { get; set; }
        public string TugName2 { get; set; }
        public string SimpleName { get; set; }
        public Nullable<int> JobStateID { get; set; }
        public string JobStateValue { get; set; }
        public string JobStateLabel { get; set; }
        public string IsCaptainConfirm { get; set; }
        public string InformCaptainTime { get; set; }
        public string CaptainConfirmTime { get; set; }
        public string DepartBaseTime { get; set; }
        public string ArrivalShipSideTime { get; set; }
        public string WorkCommencedTime { get; set; }
        public string WorkCompletedTime { get; set; }
        public string ArrivalBaseTime { get; set; }
        public string ServiceHours { get; set; }
        public string RopeUsed { get; set; }
        public Nullable<int> RopeNum { get; set; }
        public string Remark { get; set; }
        public Nullable<int> OwnerID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string CreateDate { get; set; }
        public string LastUpDate { get; set; }
    }
}
