//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_OrderInfor
    {
        public int IDX { get; set; }
        public string IsGuest { get; set; }
        public string Code { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public string CustomerName { get; set; }
        public string OrdDate { get; set; }
        public Nullable<int> ShipID { get; set; }
        public string ShipName { get; set; }
        public string LinkMan { get; set; }
        public string LinkPhone { get; set; }
        public string LinkEmail { get; set; }
        public Nullable<int> WorkStateID { get; set; }
        public string WorkStateValue { get; set; }
        public string WorkStateLabel { get; set; }
        public string Remark { get; set; }
        public Nullable<int> OwnerID { get; set; }
        public string CreateDate { get; set; }
        public Nullable<int> UserID { get; set; }
        public string LastUpDate { get; set; }
        public string HasInvoice { get; set; }
        public string HasInFlow { get; set; }
        public string CustomerCode { get; set; }
        public string CustomerName1 { get; set; }
        public string CustomerName2 { get; set; }
        public string CustomerSimpleName { get; set; }
        public Nullable<int> CustomerTypeID { get; set; }
        public string ContactPerson { get; set; }
        public string Telephone { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public string MailCode { get; set; }
        public string ShipName1 { get; set; }
        public string ShipName2 { get; set; }
        public string ShipSimpleName { get; set; }
        public Nullable<int> DeadWeight { get; set; }
        public Nullable<int> Length { get; set; }
        public Nullable<int> Width { get; set; }
        public Nullable<int> TEUS { get; set; }
        public string Class { get; set; }
        public string UserDefinedCol1 { get; set; }
        public string UserDefinedCol2 { get; set; }
        public string UserDefinedCol3 { get; set; }
        public string UserDefinedCol4 { get; set; }
    }
}
