//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_OrderService_Scheduler
    {
        public Nullable<int> OrderID { get; set; }
        public int SchedulerID { get; set; }
        public int OrderServiceID { get; set; }
        public string UserDefinedCol1 { get; set; }
    }
}
