//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_RoleMenu
    {
        public int RoleID { get; set; }
        public string RoleName { get; set; }
        public int IDX { get; set; }
        public string Page { get; set; }
        public string Menu { get; set; }
        public string MenuName { get; set; }
        public string Visible { get; set; }
        public string IsAdmin { get; set; }
        public string Remark { get; set; }
    }
}
