//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找已本地化的字符串等等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 Visual Studio 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Common {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Common() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Common", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找重写当前线程的 CurrentUICulture 
        /// 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 bw 的本地化字符串。
        /// </summary>
        internal static string ComparisonOperator_BW {
            get {
                return ResourceManager.GetString("ComparisonOperator_BW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 cn 的本地化字符串。
        /// </summary>
        internal static string ComparisonOperator_CN {
            get {
                return ResourceManager.GetString("ComparisonOperator_CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 eq 的本地化字符串。
        /// </summary>
        internal static string ComparisonOperator_EQ {
            get {
                return ResourceManager.GetString("ComparisonOperator_EQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ew 的本地化字符串。
        /// </summary>
        internal static string ComparisonOperator_EW {
            get {
                return ResourceManager.GetString("ComparisonOperator_EW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ge 的本地化字符串。
        /// </summary>
        internal static string ComparisonOperator_GE {
            get {
                return ResourceManager.GetString("ComparisonOperator_GE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 gt 的本地化字符串。
        /// </summary>
        internal static string ComparisonOperator_GT {
            get {
                return ResourceManager.GetString("ComparisonOperator_GT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 le 的本地化字符串。
        /// </summary>
        internal static string ComparisonOperator_LE {
            get {
                return ResourceManager.GetString("ComparisonOperator_LE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 lt 的本地化字符串。
        /// </summary>
        internal static string ComparisonOperator_LT {
            get {
                return ResourceManager.GetString("ComparisonOperator_LT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 4 的本地化字符串。
        /// </summary>
        internal static string ERROR_CODE {
            get {
                return ResourceManager.GetString("ERROR_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 出错 的本地化字符串。
        /// </summary>
        internal static string ERROR_MESSAGE {
            get {
                return ResourceManager.GetString("ERROR_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 3 的本地化字符串。
        /// </summary>
        internal static string EXCEPTION_CODE {
            get {
                return ResourceManager.GetString("EXCEPTION_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 异常 的本地化字符串。
        /// </summary>
        internal static string EXCEPTION_MESSAGE {
            get {
                return ResourceManager.GetString("EXCEPTION_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 2 的本地化字符串。
        /// </summary>
        internal static string FAIL_CODE {
            get {
                return ResourceManager.GetString("FAIL_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 失败 的本地化字符串。
        /// </summary>
        internal static string FAIL_MESSAGE {
            get {
                return ResourceManager.GetString("FAIL_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 3 的本地化字符串。
        /// </summary>
        internal static string HAS_INVOICE_IN_FLOW {
            get {
                return ResourceManager.GetString("HAS_INVOICE_IN_FLOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 2 的本地化字符串。
        /// </summary>
        internal static string HAS_INVOICE_NOT_IN_FLOW {
            get {
                return ResourceManager.GetString("HAS_INVOICE_NOT_IN_FLOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1 的本地化字符串。
        /// </summary>
        internal static string HAS_NO_INVOICE {
            get {
                return ResourceManager.GetString("HAS_NO_INVOICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 0 的本地化字符串。
        /// </summary>
        internal static string Information_CODE {
            get {
                return ResourceManager.GetString("Information_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您输入的用户名已被占用 的本地化字符串。
        /// </summary>
        internal static string Information_MESSAGE {
            get {
                return ResourceManager.GetString("Information_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1 的本地化字符串。
        /// </summary>
        internal static string SUCCESS_CODE {
            get {
                return ResourceManager.GetString("SUCCESS_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成功 的本地化字符串。
        /// </summary>
        internal static string SUCCESS_MESSAGE {
            get {
                return ResourceManager.GetString("SUCCESS_MESSAGE", resourceCulture);
            }
        }
    }
}
