//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找已本地化的字符串等等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 Visual Studio 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Language", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找重写当前线程的 CurrentUICulture 
        /// 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 新增 的本地化字符串。
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 通過 的本地化字符串。
        /// </summary>
        internal static string Approve_Pass {
            get {
                return ResourceManager.GetString("Approve_Pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 駁回 的本地化字符串。
        /// </summary>
        internal static string Approve_Reject {
            get {
                return ResourceManager.GetString("Approve_Reject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 排班 的本地化字符串。
        /// </summary>
        internal static string Arrangement {
            get {
                return ResourceManager.GetString("Arrangement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 排班管理 的本地化字符串。
        /// </summary>
        internal static string ArrangementManagement {
            get {
                return ResourceManager.GetString("ArrangementManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 排班ID 的本地化字符串。
        /// </summary>
        internal static string Arrangement_IDX {
            get {
                return ResourceManager.GetString("Arrangement_IDX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 排序號 的本地化字符串。
        /// </summary>
        internal static string Arrangement_SortNo {
            get {
                return ResourceManager.GetString("Arrangement_SortNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 班次 的本地化字符串。
        /// </summary>
        internal static string Arrangement_TeamName {
            get {
                return ResourceManager.GetString("Arrangement_TeamName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 拖輪ID 的本地化字符串。
        /// </summary>
        internal static string Arrangement_TugID {
            get {
                return ResourceManager.GetString("Arrangement_TugID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 拖輪名稱 的本地化字符串。
        /// </summary>
        internal static string Arrangement_TugName {
            get {
                return ResourceManager.GetString("Arrangement_TugName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工作日期 的本地化字符串。
        /// </summary>
        internal static string Arrangement_WorkDate {
            get {
                return ResourceManager.GetString("Arrangement_WorkDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 綜合信息 的本地化字符串。
        /// </summary>
        internal static string BasicInformation {
            get {
                return ResourceManager.GetString("BasicInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新增計費方案 的本地化字符串。
        /// </summary>
        internal static string BillingScheme_AddBillingScheme {
            get {
                return ResourceManager.GetString("BillingScheme_AddBillingScheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新增計費方案條目 的本地化字符串。
        /// </summary>
        internal static string BillingScheme_AddBillingSchemeItem {
            get {
                return ResourceManager.GetString("BillingScheme_AddBillingSchemeItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 編號 的本地化字符串。
        /// </summary>
        internal static string Billing_BillingCode {
            get {
                return ResourceManager.GetString("Billing_BillingCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 名稱 的本地化字符串。
        /// </summary>
        internal static string Billing_BillingName {
            get {
                return ResourceManager.GetString("Billing_BillingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 類型 的本地化字符串。
        /// </summary>
        internal static string Billing_BillingType {
            get {
                return ResourceManager.GetString("Billing_BillingType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 折扣 的本地化字符串。
        /// </summary>
        internal static string Billing_CreditAmount {
            get {
                return ResourceManager.GetString("Billing_CreditAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 內容 的本地化字符串。
        /// </summary>
        internal static string Billing_CreditContent {
            get {
                return ResourceManager.GetString("Billing_CreditContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 月份 的本地化字符串。
        /// </summary>
        internal static string Billing_Month {
            get {
                return ResourceManager.GetString("Billing_Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更改密码 的本地化字符串。
        /// </summary>
        internal static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 選擇 的本地化字符串。
        /// </summary>
        internal static string Choose {
            get {
                return ResourceManager.GetString("Choose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清除 的本地化字符串。
        /// </summary>
        internal static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清空搜索項 的本地化字符串。
        /// </summary>
        internal static string ClearSearchFilter {
            get {
                return ResourceManager.GetString("ClearSearchFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 關閉 的本地化字符串。
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 創建時間 的本地化字符串。
        /// </summary>
        internal static string CreateDate {
            get {
                return ResourceManager.GetString("CreateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 回扣單 的本地化字符串。
        /// </summary>
        internal static string Credit {
            get {
                return ResourceManager.GetString("Credit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 回扣單關聯帳單ID 的本地化字符串。
        /// </summary>
        internal static string Credit_BillingID {
            get {
                return ResourceManager.GetString("Credit_BillingID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 回扣單金額 的本地化字符串。
        /// </summary>
        internal static string Credit_CreditAmount {
            get {
                return ResourceManager.GetString("Credit_CreditAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 回扣單編號 的本地化字符串。
        /// </summary>
        internal static string Credit_CreditCode {
            get {
                return ResourceManager.GetString("Credit_CreditCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 回扣單內容 的本地化字符串。
        /// </summary>
        internal static string Credit_CreditContent {
            get {
                return ResourceManager.GetString("Credit_CreditContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 回扣單ID 的本地化字符串。
        /// </summary>
        internal static string Credit_IDX {
            get {
                return ResourceManager.GetString("Credit_IDX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 客戶 的本地化字符串。
        /// </summary>
        internal static string Customer {
            get {
                return ResourceManager.GetString("Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 計費方案 的本地化字符串。
        /// </summary>
        internal static string CustomerBillingScheme {
            get {
                return ResourceManager.GetString("CustomerBillingScheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 客戶信息 的本地化字符串。
        /// </summary>
        internal static string CustomerInformation {
            get {
                return ResourceManager.GetString("CustomerInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 客戶管理 的本地化字符串。
        /// </summary>
        internal static string CustomerManage {
            get {
                return ResourceManager.GetString("CustomerManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 客戶名稱 的本地化字符串。
        /// </summary>
        internal static string CustomerName {
            get {
                return ResourceManager.GetString("CustomerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 客戶船 的本地化字符串。
        /// </summary>
        internal static string CustomerShip {
            get {
                return ResourceManager.GetString("CustomerShip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 客戶船管理 的本地化字符串。
        /// </summary>
        internal static string CustomerShipManage {
            get {
                return ResourceManager.GetString("CustomerShipManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 船級社 的本地化字符串。
        /// </summary>
        internal static string CustomerShip_Class {
            get {
                return ResourceManager.GetString("CustomerShip_Class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 客戶ID 的本地化字符串。
        /// </summary>
        internal static string CustomerShip_CustomerID {
            get {
                return ResourceManager.GetString("CustomerShip_CustomerID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 載重噸 的本地化字符串。
        /// </summary>
        internal static string CustomerShip_DeadWeight {
            get {
                return ResourceManager.GetString("CustomerShip_DeadWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 長 的本地化字符串。
        /// </summary>
        internal static string CustomerShip_Length {
            get {
                return ResourceManager.GetString("CustomerShip_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 客戶船名稱 的本地化字符串。
        /// </summary>
        internal static string CustomerShip_Name {
            get {
                return ResourceManager.GetString("CustomerShip_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 名稱1 的本地化字符串。
        /// </summary>
        internal static string CustomerShip_Name1 {
            get {
                return ResourceManager.GetString("CustomerShip_Name1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 名稱2 的本地化字符串。
        /// </summary>
        internal static string CustomerShip_Name2 {
            get {
                return ResourceManager.GetString("CustomerShip_Name2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新增客戶船 的本地化字符串。
        /// </summary>
        internal static string CustomerShip_NewShip {
            get {
                return ResourceManager.GetString("CustomerShip_NewShip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 船型ID 的本地化字符串。
        /// </summary>
        internal static string CustomerShip_ShipTypeID {
            get {
                return ResourceManager.GetString("CustomerShip_ShipTypeID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 簡寫 的本地化字符串。
        /// </summary>
        internal static string CustomerShip_SimpleName {
            get {
                return ResourceManager.GetString("CustomerShip_SimpleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 箱量 的本地化字符串。
        /// </summary>
        internal static string CustomerShip_TEUS {
            get {
                return ResourceManager.GetString("CustomerShip_TEUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 吃水 的本地化字符串。
        /// </summary>
        internal static string CustomerShip_Width {
            get {
                return ResourceManager.GetString("CustomerShip_Width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 地址 的本地化字符串。
        /// </summary>
        internal static string Customer_Address {
            get {
                return ResourceManager.GetString("Customer_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 客戶編號 的本地化字符串。
        /// </summary>
        internal static string Customer_Code {
            get {
                return ResourceManager.GetString("Customer_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 聯繫人 的本地化字符串。
        /// </summary>
        internal static string Customer_ContactPerson {
            get {
                return ResourceManager.GetString("Customer_ContactPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 電郵 的本地化字符串。
        /// </summary>
        internal static string Customer_Email {
            get {
                return ResourceManager.GetString("Customer_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 傳真 的本地化字符串。
        /// </summary>
        internal static string Customer_Fax {
            get {
                return ResourceManager.GetString("Customer_Fax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 客戶ID 的本地化字符串。
        /// </summary>
        internal static string Customer_IDX {
            get {
                return ResourceManager.GetString("Customer_IDX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 郵編 的本地化字符串。
        /// </summary>
        internal static string Customer_MailCode {
            get {
                return ResourceManager.GetString("Customer_MailCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 姓名1 的本地化字符串。
        /// </summary>
        internal static string Customer_Name1 {
            get {
                return ResourceManager.GetString("Customer_Name1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 姓名2 的本地化字符串。
        /// </summary>
        internal static string Customer_Name2 {
            get {
                return ResourceManager.GetString("Customer_Name2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新增客戶 的本地化字符串。
        /// </summary>
        internal static string Customer_NewCustomer {
            get {
                return ResourceManager.GetString("Customer_NewCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 簡寫 的本地化字符串。
        /// </summary>
        internal static string Customer_SimpleName {
            get {
                return ResourceManager.GetString("Customer_SimpleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 電話 的本地化字符串。
        /// </summary>
        internal static string Customer_Telephone {
            get {
                return ResourceManager.GetString("Customer_Telephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 客戶類型ID 的本地化字符串。
        /// </summary>
        internal static string Customer_TypeID {
            get {
                return ResourceManager.GetString("Customer_TypeID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自定義數據 的本地化字符串。
        /// </summary>
        internal static string Custom_CustomManage {
            get {
                return ResourceManager.GetString("Custom_CustomManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 字段名称 的本地化字符串。
        /// </summary>
        internal static string Custom_Name {
            get {
                return ResourceManager.GetString("Custom_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 字段值 的本地化字符串。
        /// </summary>
        internal static string Custom_Value {
            get {
                return ResourceManager.GetString("Custom_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 刪除 的本地化字符串。
        /// </summary>
        internal static string DeleteSelectedRows {
            get {
                return ResourceManager.GetString("DeleteSelectedRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 優惠單 的本地化字符串。
        /// </summary>
        internal static string DiscountBill {
            get {
                return ResourceManager.GetString("DiscountBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 編輯 的本地化字符串。
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 財務 的本地化字符串。
        /// </summary>
        internal static string Finance {
            get {
                return ResourceManager.GetString("Finance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 日期 的本地化字符串。
        /// </summary>
        internal static string Fuelprice_EffectiveDate {
            get {
                return ResourceManager.GetString("Fuelprice_EffectiveDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 燃油價格管理 的本地化字符串。
        /// </summary>
        internal static string Fuelprice_FuelpriceManage {
            get {
                return ResourceManager.GetString("Fuelprice_FuelpriceManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 價格 的本地化字符串。
        /// </summary>
        internal static string Fuelprice_Price {
            get {
                return ResourceManager.GetString("Fuelprice_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 類別 的本地化字符串。
        /// </summary>
        internal static string Fuelprice_Type {
            get {
                return ResourceManager.GetString("Fuelprice_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 單位 的本地化字符串。
        /// </summary>
        internal static string Fuelprice_Unit {
            get {
                return ResourceManager.GetString("Fuelprice_Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 生成帳單 的本地化字符串。
        /// </summary>
        internal static string GenerateInvoice {
            get {
                return ResourceManager.GetString("GenerateInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 主頁 的本地化字符串。
        /// </summary>
        internal static string HomePage {
            get {
                return ResourceManager.GetString("HomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ID 的本地化字符串。
        /// </summary>
        internal static string IDX {
            get {
                return ResourceManager.GetString("IDX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 請選中一行記錄 的本地化字符串。
        /// </summary>
        internal static string Information_Tips_Select {
            get {
                return ResourceManager.GetString("Information_Tips_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 帳單類型 的本地化字符串。
        /// </summary>
        internal static string Invoice2_BillingType {
            get {
                return ResourceManager.GetString("Invoice2_BillingType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 選擇計費方案 的本地化字符串。
        /// </summary>
        internal static string Invoice2_ChooseBillingScheme {
            get {
                return ResourceManager.GetString("Invoice2_ChooseBillingScheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 創建審核流程 的本地化字符串。
        /// </summary>
        internal static string Invoice2_CreateFlow {
            get {
                return ResourceManager.GetString("Invoice2_CreateFlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 客戶船長 的本地化字符串。
        /// </summary>
        internal static string Invoice2_CustomerShipLength {
            get {
                return ResourceManager.GetString("Invoice2_CustomerShipLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 客戶船箱量 的本地化字符串。
        /// </summary>
        internal static string Invoice2_CustomerShipTEUS {
            get {
                return ResourceManager.GetString("Invoice2_CustomerShipTEUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 折扣 的本地化字符串。
        /// </summary>
        internal static string Invoice2_Discount {
            get {
                return ResourceManager.GetString("Invoice2_Discount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 編輯帳單和回扣單 的本地化字符串。
        /// </summary>
        internal static string Invoice2_EditCommonInvoiceAndCredit {
            get {
                return ResourceManager.GetString("Invoice2_EditCommonInvoiceAndCredit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新增帳單 的本地化字符串。
        /// </summary>
        internal static string Invoice2_GenerateCommonInvoice {
            get {
                return ResourceManager.GetString("Invoice2_GenerateCommonInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新增回扣單 的本地化字符串。
        /// </summary>
        internal static string Invoice2_GenerateCredit {
            get {
                return ResourceManager.GetString("Invoice2_GenerateCredit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 帳單月份 的本地化字符串。
        /// </summary>
        internal static string Invoice2_InvoiceMonth {
            get {
                return ResourceManager.GetString("Invoice2_InvoiceMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 帳單是否顯示船長規則 的本地化字符串。
        /// </summary>
        internal static string Invoice2_IsShowShipLengthRule {
            get {
                return ResourceManager.GetString("Invoice2_IsShowShipLengthRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 帳單是否顯示箱量規則 的本地化字符串。
        /// </summary>
        internal static string Invoice2_IsShowShipTEUSRule {
            get {
                return ResourceManager.GetString("Invoice2_IsShowShipTEUSRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 作業號(Job No.) 的本地化字符串。
        /// </summary>
        internal static string Invoice2_JobNo {
            get {
                return ResourceManager.GetString("Invoice2_JobNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 船長規則 的本地化字符串。
        /// </summary>
        internal static string Invoice2_ShipLengthRule {
            get {
                return ResourceManager.GetString("Invoice2_ShipLengthRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 箱量規則 的本地化字符串。
        /// </summary>
        internal static string Invoice2_ShipTEUSRule {
            get {
                return ResourceManager.GetString("Invoice2_ShipTEUSRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 計時方式 的本地化字符串。
        /// </summary>
        internal static string Invoice2_TimeType {
            get {
                return ResourceManager.GetString("Invoice2_TimeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查看帳單和回扣單 的本地化字符串。
        /// </summary>
        internal static string Invoice2_ViewCommonInvoiceAndCredit {
            get {
                return ResourceManager.GetString("Invoice2_ViewCommonInvoiceAndCredit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 普通帳單 的本地化字符串。
        /// </summary>
        internal static string InvoiceManage {
            get {
                return ResourceManager.GetString("InvoiceManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是管理員 的本地化字符串。
        /// </summary>
        internal static string IsAdmin {
            get {
                return ResourceManager.GetString("IsAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 必填 的本地化字符串。
        /// </summary>
        internal static string IsNull {
            get {
                return ResourceManager.GetString("IsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 作業信息 的本地化字符串。
        /// </summary>
        internal static string JobInformation {
            get {
                return ResourceManager.GetString("JobInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 語言 的本地化字符串。
        /// </summary>
        internal static string Lan {
            get {
                return ResourceManager.GetString("Lan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新時間 的本地化字符串。
        /// </summary>
        internal static string LastUpDate {
            get {
                return ResourceManager.GetString("LastUpDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模塊 的本地化字符串。
        /// </summary>
        internal static string Module {
            get {
                return ResourceManager.GetString("Module", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模塊管理 的本地化字符串。
        /// </summary>
        internal static string ModuleManage {
            get {
                return ResourceManager.GetString("ModuleManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新增模塊 的本地化字符串。
        /// </summary>
        internal static string Module_AddModule {
            get {
                return ResourceManager.GetString("Module_AddModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模塊編號 的本地化字符串。
        /// </summary>
        internal static string Module_ModuleCode {
            get {
                return ResourceManager.GetString("Module_ModuleCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模塊名稱 的本地化字符串。
        /// </summary>
        internal static string Module_ModuleName {
            get {
                return ResourceManager.GetString("Module_ModuleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系統 的本地化字符串。
        /// </summary>
        internal static string Module_System {
            get {
                return ResourceManager.GetString("Module_System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 確定 的本地化字符串。
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 訂單 的本地化字符串。
        /// </summary>
        internal static string Order {
            get {
                return ResourceManager.GetString("Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 訂單管理 的本地化字符串。
        /// </summary>
        internal static string OrderManage {
            get {
                return ResourceManager.GetString("OrderManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 訂單信息 的本地化字符串。
        /// </summary>
        internal static string OrderManage_AddOrder {
            get {
                return ResourceManager.GetString("OrderManage_AddOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 服務項 的本地化字符串。
        /// </summary>
        internal static string OrderManage_Serivces {
            get {
                return ResourceManager.GetString("OrderManage_Serivces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 訂單調度 的本地化字符串。
        /// </summary>
        internal static string OrderScheduling {
            get {
                return ResourceManager.GetString("OrderScheduling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 組織結構 的本地化字符串。
        /// </summary>
        internal static string Organization {
            get {
                return ResourceManager.GetString("Organization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 組織結構管理 的本地化字符串。
        /// </summary>
        internal static string OrganizationManage {
            get {
                return ResourceManager.GetString("OrganizationManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 部門 的本地化字符串。
        /// </summary>
        internal static string Org_Dept {
            get {
                return ResourceManager.GetString("Org_Dept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 電郵 的本地化字符串。
        /// </summary>
        internal static string Org_Email {
            get {
                return ResourceManager.GetString("Org_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 域 的本地化字符串。
        /// </summary>
        internal static string Org_Lan {
            get {
                return ResourceManager.GetString("Org_Lan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 域用戶名 的本地化字符串。
        /// </summary>
        internal static string Org_LanUserName {
            get {
                return ResourceManager.GetString("Org_LanUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 名稱1 的本地化字符串。
        /// </summary>
        internal static string Org_Name1 {
            get {
                return ResourceManager.GetString("Org_Name1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 名稱2 的本地化字符串。
        /// </summary>
        internal static string Org_Name2 {
            get {
                return ResourceManager.GetString("Org_Name2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密碼 的本地化字符串。
        /// </summary>
        internal static string Org_Pwd {
            get {
                return ResourceManager.GetString("Org_Pwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 科室 的本地化字符串。
        /// </summary>
        internal static string Org_Sec {
            get {
                return ResourceManager.GetString("Org_Sec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 性別 的本地化字符串。
        /// </summary>
        internal static string Org_Sex {
            get {
                return ResourceManager.GetString("Org_Sex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 電話 的本地化字符串。
        /// </summary>
        internal static string Org_Tel {
            get {
                return ResourceManager.GetString("Org_Tel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用戶名 的本地化字符串。
        /// </summary>
        internal static string Org_UserName {
            get {
                return ResourceManager.GetString("Org_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工號 的本地化字符串。
        /// </summary>
        internal static string Org_WorkNumber {
            get {
                return ResourceManager.GetString("Org_WorkNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 角色 的本地化字符串。
        /// </summary>
        internal static string OwnerID {
            get {
                return ResourceManager.GetString("OwnerID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 預覽 的本地化字符串。
        /// </summary>
        internal static string Preview {
            get {
                return ResourceManager.GetString("Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 刷新 的本地化字符串。
        /// </summary>
        internal static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 備註 的本地化字符串。
        /// </summary>
        internal static string Remark {
            get {
                return ResourceManager.GetString("Remark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 報表分析 的本地化字符串。
        /// </summary>
        internal static string Report {
            get {
                return ResourceManager.GetString("Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全包半包匯總 的本地化字符串。
        /// </summary>
        internal static string Report_BillType {
            get {
                return ResourceManager.GetString("Report_BillType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 客戶營業額匯總 的本地化字符串。
        /// </summary>
        internal static string Report_Customer {
            get {
                return ResourceManager.GetString("Report_Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 結束日期 的本地化字符串。
        /// </summary>
        internal static string Report_EndDate {
            get {
                return ResourceManager.GetString("Report_EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 起始日期 的本地化字符串。
        /// </summary>
        internal static string Report_StartDate {
            get {
                return ResourceManager.GetString("Report_StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 拖輪營業額匯總 的本地化字符串。
        /// </summary>
        internal static string Report_Tug {
            get {
                return ResourceManager.GetString("Report_Tug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重置 的本地化字符串。
        /// </summary>
        internal static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 角色 的本地化字符串。
        /// </summary>
        internal static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 角色管理 的本地化字符串。
        /// </summary>
        internal static string RoleManage {
            get {
                return ResourceManager.GetString("RoleManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 角色菜單 的本地化字符串。
        /// </summary>
        internal static string RoleMenu {
            get {
                return ResourceManager.GetString("RoleMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 角色菜單關聯 的本地化字符串。
        /// </summary>
        internal static string RoleMenuManage {
            get {
                return ResourceManager.GetString("RoleMenuManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 菜單ID 的本地化字符串。
        /// </summary>
        internal static string RoleMenu_Menu {
            get {
                return ResourceManager.GetString("RoleMenu_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 菜單名 的本地化字符串。
        /// </summary>
        internal static string RoleMenu_MenuName {
            get {
                return ResourceManager.GetString("RoleMenu_MenuName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 頁面 的本地化字符串。
        /// </summary>
        internal static string RoleMenu_Page {
            get {
                return ResourceManager.GetString("RoleMenu_Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否可見 的本地化字符串。
        /// </summary>
        internal static string RoleMenu_Visible {
            get {
                return ResourceManager.GetString("RoleMenu_Visible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 角色模塊 的本地化字符串。
        /// </summary>
        internal static string RoleModule {
            get {
                return ResourceManager.GetString("RoleModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 角色模塊管理 的本地化字符串。
        /// </summary>
        internal static string RoleModuleManage {
            get {
                return ResourceManager.GetString("RoleModuleManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 角色用戶 的本地化字符串。
        /// </summary>
        internal static string RoleUser {
            get {
                return ResourceManager.GetString("RoleUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 角色用戶管理 的本地化字符串。
        /// </summary>
        internal static string RoleUserManage {
            get {
                return ResourceManager.GetString("RoleUserManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新增用戶 的本地化字符串。
        /// </summary>
        internal static string RoleUser_AddUser {
            get {
                return ResourceManager.GetString("RoleUser_AddUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新增角色 的本地化字符串。
        /// </summary>
        internal static string Role_AddRole {
            get {
                return ResourceManager.GetString("Role_AddRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 部門 的本地化字符串。
        /// </summary>
        internal static string Role_Dept {
            get {
                return ResourceManager.GetString("Role_Dept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 角色名稱 的本地化字符串。
        /// </summary>
        internal static string Role_RoleName {
            get {
                return ResourceManager.GetString("Role_RoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系統 的本地化字符串。
        /// </summary>
        internal static string Role_System {
            get {
                return ResourceManager.GetString("Role_System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 搜索 的本地化字符串。
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 服務調度 的本地化字符串。
        /// </summary>
        internal static string ServiceScheduler {
            get {
                return ResourceManager.GetString("ServiceScheduler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 服務狀態 的本地化字符串。
        /// </summary>
        internal static string ServiceStatus {
            get {
                return ResourceManager.GetString("ServiceStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新增拖輪調度 的本地化字符串。
        /// </summary>
        internal static string ServiceStatus_AddScheduler {
            get {
                return ResourceManager.GetString("ServiceStatus_AddScheduler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 選擇拖輪 的本地化字符串。
        /// </summary>
        internal static string ServiceStatus_ChooseTug {
            get {
                return ResourceManager.GetString("ServiceStatus_ChooseTug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 拖輪調度 的本地化字符串。
        /// </summary>
        internal static string ServiceStatus_TugScheduler {
            get {
                return ResourceManager.GetString("ServiceStatus_TugScheduler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 拖輪調度狀態 的本地化字符串。
        /// </summary>
        internal static string ServiceStatus_TugSchedulerStatus {
            get {
                return ResourceManager.GetString("ServiceStatus_TugSchedulerStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 特殊帳單 的本地化字符串。
        /// </summary>
        internal static string SpecialInvoiceManage {
            get {
                return ResourceManager.GetString("SpecialInvoiceManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提交 的本地化字符串。
        /// </summary>
        internal static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提交審核 的本地化字符串。
        /// </summary>
        internal static string SubmitForApproval {
            get {
                return ResourceManager.GetString("SubmitForApproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 確定刪除所選記錄？ 的本地化字符串。
        /// </summary>
        internal static string SureDelete {
            get {
                return ResourceManager.GetString("SureDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已完成 的本地化字符串。
        /// </summary>
        internal static string Task_Approved {
            get {
                return ResourceManager.GetString("Task_Approved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 待完成 的本地化字符串。
        /// </summary>
        internal static string Task_NeedApprove {
            get {
                return ResourceManager.GetString("Task_NeedApprove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 駁回原因 的本地化字符串。
        /// </summary>
        internal static string Task_RejectReason {
            get {
                return ResourceManager.GetString("Task_RejectReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 任務 的本地化字符串。
        /// </summary>
        internal static string Task_Task {
            get {
                return ResourceManager.GetString("Task_Task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 任務管理 的本地化字符串。
        /// </summary>
        internal static string Task_TaskManage {
            get {
                return ResourceManager.GetString("Task_TaskManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 拖輪 的本地化字符串。
        /// </summary>
        internal static string TugInfor {
            get {
                return ResourceManager.GetString("TugInfor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 拖輪管理 的本地化字符串。
        /// </summary>
        internal static string TugInforManage {
            get {
                return ResourceManager.GetString("TugInforManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 船級社 的本地化字符串。
        /// </summary>
        internal static string TugInfor_Class {
            get {
                return ResourceManager.GetString("TugInfor_Class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 拖輪編號 的本地化字符串。
        /// </summary>
        internal static string TugInfor_Code {
            get {
                return ResourceManager.GetString("TugInfor_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否停用 的本地化字符串。
        /// </summary>
        internal static string TugInfor_Disable {
            get {
                return ResourceManager.GetString("TugInfor_Disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 拖輪ID 的本地化字符串。
        /// </summary>
        internal static string TugInfor_IDX {
            get {
                return ResourceManager.GetString("TugInfor_IDX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 長度 的本地化字符串。
        /// </summary>
        internal static string TugInfor_Length {
            get {
                return ResourceManager.GetString("TugInfor_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 名稱1 的本地化字符串。
        /// </summary>
        internal static string TugInfor_Name1 {
            get {
                return ResourceManager.GetString("TugInfor_Name1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 名稱2 的本地化字符串。
        /// </summary>
        internal static string TugInfor_Name2 {
            get {
                return ResourceManager.GetString("TugInfor_Name2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 增加拖輪 的本地化字符串。
        /// </summary>
        internal static string TugInfor_NewTug {
            get {
                return ResourceManager.GetString("TugInfor_NewTug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 馬力 的本地化字符串。
        /// </summary>
        internal static string TugInfor_Power {
            get {
                return ResourceManager.GetString("TugInfor_Power", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 簡寫 的本地化字符串。
        /// </summary>
        internal static string TugInfor_SimpleName {
            get {
                return ResourceManager.GetString("TugInfor_SimpleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 航速 的本地化字符串。
        /// </summary>
        internal static string TugInfor_Speed {
            get {
                return ResourceManager.GetString("TugInfor_Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 寬度 的本地化字符串。
        /// </summary>
        internal static string TugInfor_Width {
            get {
                return ResourceManager.GetString("TugInfor_Width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 拖輪名稱 的本地化字符串。
        /// </summary>
        internal static string TugName {
            get {
                return ResourceManager.GetString("TugName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 拖輪狀態 的本地化字符串。
        /// </summary>
        internal static string TugStatus {
            get {
                return ResourceManager.GetString("TugStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自定義字段1 的本地化字符串。
        /// </summary>
        internal static string UserDefinedCol1 {
            get {
                return ResourceManager.GetString("UserDefinedCol1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自定義字段10 的本地化字符串。
        /// </summary>
        internal static string UserDefinedCol10 {
            get {
                return ResourceManager.GetString("UserDefinedCol10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自定義字段2 的本地化字符串。
        /// </summary>
        internal static string UserDefinedCol2 {
            get {
                return ResourceManager.GetString("UserDefinedCol2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自定義字段3 的本地化字符串。
        /// </summary>
        internal static string UserDefinedCol3 {
            get {
                return ResourceManager.GetString("UserDefinedCol3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自定義字段4 的本地化字符串。
        /// </summary>
        internal static string UserDefinedCol4 {
            get {
                return ResourceManager.GetString("UserDefinedCol4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自定義字段5 的本地化字符串。
        /// </summary>
        internal static string UserDefinedCol5 {
            get {
                return ResourceManager.GetString("UserDefinedCol5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自定義字段6 的本地化字符串。
        /// </summary>
        internal static string UserDefinedCol6 {
            get {
                return ResourceManager.GetString("UserDefinedCol6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自定義字段7 的本地化字符串。
        /// </summary>
        internal static string UserDefinedCol7 {
            get {
                return ResourceManager.GetString("UserDefinedCol7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自定義字段8 的本地化字符串。
        /// </summary>
        internal static string UserDefinedCol8 {
            get {
                return ResourceManager.GetString("UserDefinedCol8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自定義字段9 的本地化字符串。
        /// </summary>
        internal static string UserDefinedCol9 {
            get {
                return ResourceManager.GetString("UserDefinedCol9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用戶 的本地化字符串。
        /// </summary>
        internal static string UserID {
            get {
                return ResourceManager.GetString("UserID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 人員信息 的本地化字符串。
        /// </summary>
        internal static string UserInfor {
            get {
                return ResourceManager.GetString("UserInfor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 人員信息管理 的本地化字符串。
        /// </summary>
        internal static string UserInforManage {
            get {
                return ResourceManager.GetString("UserInforManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 返回登陸頁面 的本地化字符串。
        /// </summary>
        internal static string UserInfor_BackLogin {
            get {
                return ResourceManager.GetString("UserInfor_BackLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改密碼 的本地化字符串。
        /// </summary>
        internal static string UserInfor_ChangePwd {
            get {
                return ResourceManager.GetString("UserInfor_ChangePwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 部 門 的本地化字符串。
        /// </summary>
        internal static string UserInfor_Dept {
            get {
                return ResourceManager.GetString("UserInfor_Dept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 郵 箱 的本地化字符串。
        /// </summary>
        internal static string UserInfor_Email {
            get {
                return ResourceManager.GetString("UserInfor_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登 錄 的本地化字符串。
        /// </summary>
        internal static string UserInfor_Login {
            get {
                return ResourceManager.GetString("UserInfor_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 退出 的本地化字符串。
        /// </summary>
        internal static string UserInfor_LoginOut {
            get {
                return ResourceManager.GetString("UserInfor_LoginOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模塊定義 的本地化字符串。
        /// </summary>
        internal static string UserInfor_ModuleManage {
            get {
                return ResourceManager.GetString("UserInfor_ModuleManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 中文名 的本地化字符串。
        /// </summary>
        internal static string UserInfor_Name1 {
            get {
                return ResourceManager.GetString("UserInfor_Name1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 英文名 的本地化字符串。
        /// </summary>
        internal static string UserInfor_Name2 {
            get {
                return ResourceManager.GetString("UserInfor_Name2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新密碼 的本地化字符串。
        /// </summary>
        internal static string UserInfor_NewPwd {
            get {
                return ResourceManager.GetString("UserInfor_NewPwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新增用戶 的本地化字符串。
        /// </summary>
        internal static string UserInfor_NewUser {
            get {
                return ResourceManager.GetString("UserInfor_NewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 確 定 的本地化字符串。
        /// </summary>
        internal static string UserInfor_OK {
            get {
                return ResourceManager.GetString("UserInfor_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 原密碼 的本地化字符串。
        /// </summary>
        internal static string UserInfor_OriginalPwd {
            get {
                return ResourceManager.GetString("UserInfor_OriginalPwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 權限管理 的本地化字符串。
        /// </summary>
        internal static string UserInfor_permissions {
            get {
                return ResourceManager.GetString("UserInfor_permissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密 碼 的本地化字符串。
        /// </summary>
        internal static string UserInfor_Pwd {
            get {
                return ResourceManager.GetString("UserInfor_Pwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 註 冊 的本地化字符串。
        /// </summary>
        internal static string UserInfor_Register {
            get {
                return ResourceManager.GetString("UserInfor_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 再次輸入新密碼 的本地化字符串。
        /// </summary>
        internal static string UserInfor_RepeatPwd {
            get {
                return ResourceManager.GetString("UserInfor_RepeatPwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 角色定義 的本地化字符串。
        /// </summary>
        internal static string UserInfor_RoleManage {
            get {
                return ResourceManager.GetString("UserInfor_RoleManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 角色菜單 的本地化字符串。
        /// </summary>
        internal static string UserInfor_RoleMenuManage {
            get {
                return ResourceManager.GetString("UserInfor_RoleMenuManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 角色模塊 的本地化字符串。
        /// </summary>
        internal static string UserInfor_RoleModuleManage {
            get {
                return ResourceManager.GetString("UserInfor_RoleModuleManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 角色用戶 的本地化字符串。
        /// </summary>
        internal static string UserInfor_RoleUserManage {
            get {
                return ResourceManager.GetString("UserInfor_RoleUserManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 科 室 的本地化字符串。
        /// </summary>
        internal static string UserInfor_Sec {
            get {
                return ResourceManager.GetString("UserInfor_Sec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 性 別 的本地化字符串。
        /// </summary>
        internal static string UserInfor_Sex {
            get {
                return ResourceManager.GetString("UserInfor_Sex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 註冊 的本地化字符串。
        /// </summary>
        internal static string UserInfor_SignUp {
            get {
                return ResourceManager.GetString("UserInfor_SignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 電 話 的本地化字符串。
        /// </summary>
        internal static string UserInfor_Tel {
            get {
                return ResourceManager.GetString("UserInfor_Tel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 個人信息 的本地化字符串。
        /// </summary>
        internal static string UserInfor_UserInfor {
            get {
                return ResourceManager.GetString("UserInfor_UserInfor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用戶名 的本地化字符串。
        /// </summary>
        internal static string UserInfor_UserName {
            get {
                return ResourceManager.GetString("UserInfor_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工 號 的本地化字符串。
        /// </summary>
        internal static string UserInfor_WorkNumber {
            get {
                return ResourceManager.GetString("UserInfor_WorkNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 優惠單編號 的本地化字符串。
        /// </summary>
        internal static string V_Billing4_BillingCode {
            get {
                return ResourceManager.GetString("V_Billing4_BillingCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 內容 的本地化字符串。
        /// </summary>
        internal static string V_Billing4_Content {
            get {
                return ResourceManager.GetString("V_Billing4_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 單據類型 的本地化字符串。
        /// </summary>
        internal static string V_Billing4_InvoiceType {
            get {
                return ResourceManager.GetString("V_Billing4_InvoiceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 金額 的本地化字符串。
        /// </summary>
        internal static string V_Billing4_Money {
            get {
                return ResourceManager.GetString("V_Billing4_Money", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 標題 的本地化字符串。
        /// </summary>
        internal static string V_Billing4_Title {
            get {
                return ResourceManager.GetString("V_Billing4_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 關聯的模板ID 的本地化字符串。
        /// </summary>
        internal static string V_BillingItemTemplate_BillingTemplateID {
            get {
                return ResourceManager.GetString("V_BillingItemTemplate_BillingTemplateID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 幣種 的本地化字符串。
        /// </summary>
        internal static string V_BillingItemTemplate_Currency {
            get {
                return ResourceManager.GetString("V_BillingItemTemplate_Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 折扣 的本地化字符串。
        /// </summary>
        internal static string V_BillingItemTemplate_Discount {
            get {
                return ResourceManager.GetString("V_BillingItemTemplate_Discount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 有效期 的本地化字符串。
        /// </summary>
        internal static string V_BillingItemTemplate_ExpiryDate {
            get {
                return ResourceManager.GetString("V_BillingItemTemplate_ExpiryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模板項ID 的本地化字符串。
        /// </summary>
        internal static string V_BillingItemTemplate_IDX {
            get {
                return ResourceManager.GetString("V_BillingItemTemplate_IDX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 服務項ID 的本地化字符串。
        /// </summary>
        internal static string V_BillingItemTemplate_ItemID {
            get {
                return ResourceManager.GetString("V_BillingItemTemplate_ItemID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 服務項 的本地化字符串。
        /// </summary>
        internal static string V_BillingItemTemplate_ItemLabel {
            get {
                return ResourceManager.GetString("V_BillingItemTemplate_ItemLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 服務項值 的本地化字符串。
        /// </summary>
        internal static string V_BillingItemTemplate_ItemValue {
            get {
                return ResourceManager.GetString("V_BillingItemTemplate_ItemValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 船長規則 的本地化字符串。
        /// </summary>
        internal static string V_BillingItemTemplate_ShipLength {
            get {
                return ResourceManager.GetString("V_BillingItemTemplate_ShipLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 箱量規則 的本地化字符串。
        /// </summary>
        internal static string V_BillingItemTemplate_ShipTEUS {
            get {
                return ResourceManager.GetString("V_BillingItemTemplate_ShipTEUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 位置ID 的本地化字符串。
        /// </summary>
        internal static string V_BillingItemTemplate_TypeID {
            get {
                return ResourceManager.GetString("V_BillingItemTemplate_TypeID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 位置 的本地化字符串。
        /// </summary>
        internal static string V_BillingItemTemplate_TypeLabel {
            get {
                return ResourceManager.GetString("V_BillingItemTemplate_TypeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 位置值 的本地化字符串。
        /// </summary>
        internal static string V_BillingItemTemplate_TypeValue {
            get {
                return ResourceManager.GetString("V_BillingItemTemplate_TypeValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 單價 的本地化字符串。
        /// </summary>
        internal static string V_BillingItemTemplate_UnitPrice {
            get {
                return ResourceManager.GetString("V_BillingItemTemplate_UnitPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模板編碼 的本地化字符串。
        /// </summary>
        internal static string V_BillingTemplate_BillingTemplateCode {
            get {
                return ResourceManager.GetString("V_BillingTemplate_BillingTemplateCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模板名稱 的本地化字符串。
        /// </summary>
        internal static string V_BillingTemplate_BillingTemplateName {
            get {
                return ResourceManager.GetString("V_BillingTemplate_BillingTemplateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模板類型ID 的本地化字符串。
        /// </summary>
        internal static string V_BillingTemplate_BillingTemplateTypeID {
            get {
                return ResourceManager.GetString("V_BillingTemplate_BillingTemplateTypeID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模板類型 的本地化字符串。
        /// </summary>
        internal static string V_BillingTemplate_BillingTemplateTypeLabel {
            get {
                return ResourceManager.GetString("V_BillingTemplate_BillingTemplateTypeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模板類型值 的本地化字符串。
        /// </summary>
        internal static string V_BillingTemplate_BillingTemplateTypeValue {
            get {
                return ResourceManager.GetString("V_BillingTemplate_BillingTemplateTypeValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 客戶ID 的本地化字符串。
        /// </summary>
        internal static string V_BillingTemplate_CustomerID {
            get {
                return ResourceManager.GetString("V_BillingTemplate_CustomerID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 客戶計費模版ID 的本地化字符串。
        /// </summary>
        internal static string V_BillingTemplate_IDX {
            get {
                return ResourceManager.GetString("V_BillingTemplate_IDX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模板回扣 的本地化字符串。
        /// </summary>
        internal static string V_BillingTemplate_TemplateCreditContent {
            get {
                return ResourceManager.GetString("V_BillingTemplate_TemplateCreditContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模板計時方式ID 的本地化字符串。
        /// </summary>
        internal static string V_BillingTemplate_TimeTypeID {
            get {
                return ResourceManager.GetString("V_BillingTemplate_TimeTypeID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模板計時方式 的本地化字符串。
        /// </summary>
        internal static string V_BillingTemplate_TimeTypeLabel {
            get {
                return ResourceManager.GetString("V_BillingTemplate_TimeTypeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模板計時方式值 的本地化字符串。
        /// </summary>
        internal static string V_BillingTemplate_TimeTypeValue {
            get {
                return ResourceManager.GetString("V_BillingTemplate_TimeTypeValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 總價 的本地化字符串。
        /// </summary>
        internal static string V_Billing_Amount {
            get {
                return ResourceManager.GetString("V_Billing_Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 帳單編號 的本地化字符串。
        /// </summary>
        internal static string V_Billing_BillingCode {
            get {
                return ResourceManager.GetString("V_Billing_BillingCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 計費方案模板ID 的本地化字符串。
        /// </summary>
        internal static string V_Billing_BillingTemplateID {
            get {
                return ResourceManager.GetString("V_Billing_BillingTemplateID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 計費方案模板名稱 的本地化字符串。
        /// </summary>
        internal static string V_Billing_BillingTemplateName {
            get {
                return ResourceManager.GetString("V_Billing_BillingTemplateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 計費類型 的本地化字符串。
        /// </summary>
        internal static string V_Billing_BillingTemplateTypeLabel {
            get {
                return ResourceManager.GetString("V_Billing_BillingTemplateTypeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否顯示船長規則 的本地化字符串。
        /// </summary>
        internal static string V_Billing_IsShowShipLengthRule {
            get {
                return ResourceManager.GetString("V_Billing_IsShowShipLengthRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否顯示箱量規則 的本地化字符串。
        /// </summary>
        internal static string V_Billing_IsShowShipTEUSRule {
            get {
                return ResourceManager.GetString("V_Billing_IsShowShipTEUSRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 階段 的本地化字符串。
        /// </summary>
        internal static string V_Billing_Phase {
            get {
                return ResourceManager.GetString("V_Billing_Phase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 計費方案船長規則 的本地化字符串。
        /// </summary>
        internal static string V_Billing_ShipLength {
            get {
                return ResourceManager.GetString("V_Billing_ShipLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 計費方案箱量規則 的本地化字符串。
        /// </summary>
        internal static string V_Billing_ShipTEUS {
            get {
                return ResourceManager.GetString("V_Billing_ShipTEUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 狀態 的本地化字符串。
        /// </summary>
        internal static string V_Billing_Status {
            get {
                return ResourceManager.GetString("V_Billing_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 計時方式 的本地化字符串。
        /// </summary>
        internal static string V_Billing_TimeTypeLabel {
            get {
                return ResourceManager.GetString("V_Billing_TimeTypeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 總計價格 的本地化字符串。
        /// </summary>
        internal static string V_OrderBilling_Amount {
            get {
                return ResourceManager.GetString("V_OrderBilling_Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 帳單編號 的本地化字符串。
        /// </summary>
        internal static string V_OrderBilling_BillingCode {
            get {
                return ResourceManager.GetString("V_OrderBilling_BillingCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 帳單ID 的本地化字符串。
        /// </summary>
        internal static string V_OrderBilling_BillingID {
            get {
                return ResourceManager.GetString("V_OrderBilling_BillingID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 帳單名稱 的本地化字符串。
        /// </summary>
        internal static string V_OrderBilling_BillingName {
            get {
                return ResourceManager.GetString("V_OrderBilling_BillingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 帳單備註 的本地化字符串。
        /// </summary>
        internal static string V_OrderBilling_BillingRemark {
            get {
                return ResourceManager.GetString("V_OrderBilling_BillingRemark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 帳單類型ID 的本地化字符串。
        /// </summary>
        internal static string V_OrderBilling_BillingTypeID {
            get {
                return ResourceManager.GetString("V_OrderBilling_BillingTypeID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 帳單類型 的本地化字符串。
        /// </summary>
        internal static string V_OrderBilling_BillingTypeLabel {
            get {
                return ResourceManager.GetString("V_OrderBilling_BillingTypeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 帳單類型值 的本地化字符串。
        /// </summary>
        internal static string V_OrderBilling_BillingTypeValue {
            get {
                return ResourceManager.GetString("V_OrderBilling_BillingTypeValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 作業號 的本地化字符串。
        /// </summary>
        internal static string V_OrderBilling_JobNo {
            get {
                return ResourceManager.GetString("V_OrderBilling_JobNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 帳單月份 的本地化字符串。
        /// </summary>
        internal static string V_OrderBilling_Month {
            get {
                return ResourceManager.GetString("V_OrderBilling_Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 帳單階段 的本地化字符串。
        /// </summary>
        internal static string V_OrderBilling_Phase {
            get {
                return ResourceManager.GetString("V_OrderBilling_Phase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 帳單狀態 的本地化字符串。
        /// </summary>
        internal static string V_OrderBilling_Status {
            get {
                return ResourceManager.GetString("V_OrderBilling_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 次序 的本地化字符串。
        /// </summary>
        internal static string V_OrderBilling_TimesNo {
            get {
                return ResourceManager.GetString("V_OrderBilling_TimesNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 計時方式ID 的本地化字符串。
        /// </summary>
        internal static string V_OrderBilling_TimeTypeID {
            get {
                return ResourceManager.GetString("V_OrderBilling_TimeTypeID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 計時方式 的本地化字符串。
        /// </summary>
        internal static string V_OrderBilling_TimeTypeLabel {
            get {
                return ResourceManager.GetString("V_OrderBilling_TimeTypeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 計時方式值 的本地化字符串。
        /// </summary>
        internal static string V_OrderBilling_TimeTypeValue {
            get {
                return ResourceManager.GetString("V_OrderBilling_TimeTypeValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 大拖輪數量 的本地化字符串。
        /// </summary>
        internal static string V_OrderInfor_BigTugNum {
            get {
                return ResourceManager.GetString("V_OrderInfor_BigTugNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 訂單編號 的本地化字符串。
        /// </summary>
        internal static string V_OrderInfor_Code {
            get {
                return ResourceManager.GetString("V_OrderInfor_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 客戶ID 的本地化字符串。
        /// </summary>
        internal static string V_OrderInfor_CustomerID {
            get {
                return ResourceManager.GetString("V_OrderInfor_CustomerID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 客戶名稱 的本地化字符串。
        /// </summary>
        internal static string V_OrderInfor_CustomerName {
            get {
                return ResourceManager.GetString("V_OrderInfor_CustomerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 預估完成時間 的本地化字符串。
        /// </summary>
        internal static string V_OrderInfor_EstimatedCompletionTime {
            get {
                return ResourceManager.GetString("V_OrderInfor_EstimatedCompletionTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否在流程中 的本地化字符串。
        /// </summary>
        internal static string V_OrderInfor_HasInFlow {
            get {
                return ResourceManager.GetString("V_OrderInfor_HasInFlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否已有帳單 的本地化字符串。
        /// </summary>
        internal static string V_OrderInfor_HasInvoice {
            get {
                return ResourceManager.GetString("V_OrderInfor_HasInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 訂單ID 的本地化字符串。
        /// </summary>
        internal static string V_OrderInfor_IDX {
            get {
                return ResourceManager.GetString("V_OrderInfor_IDX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否客戶下單 的本地化字符串。
        /// </summary>
        internal static string V_OrderInfor_IsGuest {
            get {
                return ResourceManager.GetString("V_OrderInfor_IsGuest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 聯繫人電郵 的本地化字符串。
        /// </summary>
        internal static string V_OrderInfor_LinkEmail {
            get {
                return ResourceManager.GetString("V_OrderInfor_LinkEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 聯繫人名稱 的本地化字符串。
        /// </summary>
        internal static string V_OrderInfor_LinkMan {
            get {
                return ResourceManager.GetString("V_OrderInfor_LinkMan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 聯繫人電話 的本地化字符串。
        /// </summary>
        internal static string V_OrderInfor_LinkPhone {
            get {
                return ResourceManager.GetString("V_OrderInfor_LinkPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 5000BHP拖轮數量 的本地化字符串。
        /// </summary>
        internal static string V_OrderInfor_MiddleTugNum {
            get {
                return ResourceManager.GetString("V_OrderInfor_MiddleTugNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下單日期 的本地化字符串。
        /// </summary>
        internal static string V_OrderInfor_OrdDate {
            get {
                return ResourceManager.GetString("V_OrderInfor_OrdDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 服務內容ID 的本地化字符串。
        /// </summary>
        internal static string V_OrderInfor_ServiceNatureIDS {
            get {
                return ResourceManager.GetString("V_OrderInfor_ServiceNatureIDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 服務內容名稱 的本地化字符串。
        /// </summary>
        internal static string V_OrderInfor_ServiceNatureNames {
            get {
                return ResourceManager.GetString("V_OrderInfor_ServiceNatureNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 客戶船ID 的本地化字符串。
        /// </summary>
        internal static string V_OrderInfor_ShipID {
            get {
                return ResourceManager.GetString("V_OrderInfor_ShipID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 客戶船名稱 的本地化字符串。
        /// </summary>
        internal static string V_OrderInfor_ShipName {
            get {
                return ResourceManager.GetString("V_OrderInfor_ShipName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 小拖輪數量 的本地化字符串。
        /// </summary>
        internal static string V_OrderInfor_SmallTugNum {
            get {
                return ResourceManager.GetString("V_OrderInfor_SmallTugNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工作日期 的本地化字符串。
        /// </summary>
        internal static string V_OrderInfor_WorkDate {
            get {
                return ResourceManager.GetString("V_OrderInfor_WorkDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工作地點 的本地化字符串。
        /// </summary>
        internal static string V_OrderInfor_WorkPlace {
            get {
                return ResourceManager.GetString("V_OrderInfor_WorkPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工作狀態ID 的本地化字符串。
        /// </summary>
        internal static string V_OrderInfor_WorkStateID {
            get {
                return ResourceManager.GetString("V_OrderInfor_WorkStateID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工作狀態 的本地化字符串。
        /// </summary>
        internal static string V_OrderInfor_WorkStateLabel {
            get {
                return ResourceManager.GetString("V_OrderInfor_WorkStateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工作狀態值 的本地化字符串。
        /// </summary>
        internal static string V_OrderInfor_WorkStateValue {
            get {
                return ResourceManager.GetString("V_OrderInfor_WorkStateValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工作時間 的本地化字符串。
        /// </summary>
        internal static string V_OrderInfor_WorkTime {
            get {
                return ResourceManager.GetString("V_OrderInfor_WorkTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 到廠時間 的本地化字符串。
        /// </summary>
        internal static string V_OrderScheduler_ArrivalBaseTime {
            get {
                return ResourceManager.GetString("V_OrderScheduler_ArrivalBaseTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 到船時間 的本地化字符串。
        /// </summary>
        internal static string V_OrderScheduler_ArrivalShipSideTime {
            get {
                return ResourceManager.GetString("V_OrderScheduler_ArrivalShipSideTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 船長確認時間 的本地化字符串。
        /// </summary>
        internal static string V_OrderScheduler_CaptainConfirmTime {
            get {
                return ResourceManager.GetString("V_OrderScheduler_CaptainConfirmTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 選擇拖輪 的本地化字符串。
        /// </summary>
        internal static string V_OrderScheduler_ChooseTug {
            get {
                return ResourceManager.GetString("V_OrderScheduler_ChooseTug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 離廠時間 的本地化字符串。
        /// </summary>
        internal static string V_OrderScheduler_DepartBaseTime {
            get {
                return ResourceManager.GetString("V_OrderScheduler_DepartBaseTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 調度ID 的本地化字符串。
        /// </summary>
        internal static string V_OrderScheduler_IDX {
            get {
                return ResourceManager.GetString("V_OrderScheduler_IDX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 通知船長時間 的本地化字符串。
        /// </summary>
        internal static string V_OrderScheduler_InformCaptainTime {
            get {
                return ResourceManager.GetString("V_OrderScheduler_InformCaptainTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 船長是否確認 的本地化字符串。
        /// </summary>
        internal static string V_OrderScheduler_IsCaptainConfirm {
            get {
                return ResourceManager.GetString("V_OrderScheduler_IsCaptainConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 調度作業狀態ID 的本地化字符串。
        /// </summary>
        internal static string V_OrderScheduler_JobStateID {
            get {
                return ResourceManager.GetString("V_OrderScheduler_JobStateID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 調圖作業狀態 的本地化字符串。
        /// </summary>
        internal static string V_OrderScheduler_JobStateLabel {
            get {
                return ResourceManager.GetString("V_OrderScheduler_JobStateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 拖輪名稱1 的本地化字符串。
        /// </summary>
        internal static string V_OrderScheduler_Name1 {
            get {
                return ResourceManager.GetString("V_OrderScheduler_Name1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 拖輪名稱2 的本地化字符串。
        /// </summary>
        internal static string V_OrderScheduler_Name2 {
            get {
                return ResourceManager.GetString("V_OrderScheduler_Name2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 調度關聯的訂單ID 的本地化字符串。
        /// </summary>
        internal static string V_OrderScheduler_OrderID {
            get {
                return ResourceManager.GetString("V_OrderScheduler_OrderID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 訂單服務ID 的本地化字符串。
        /// </summary>
        internal static string V_OrderScheduler_OrderServiceID {
            get {
                return ResourceManager.GetString("V_OrderScheduler_OrderServiceID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 使用拖纜數量 的本地化字符串。
        /// </summary>
        internal static string V_OrderScheduler_RopeNum {
            get {
                return ResourceManager.GetString("V_OrderScheduler_RopeNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否使用拖纜 的本地化字符串。
        /// </summary>
        internal static string V_OrderScheduler_RopeUsed {
            get {
                return ResourceManager.GetString("V_OrderScheduler_RopeUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 調度地點 的本地化字符串。
        /// </summary>
        internal static string V_OrderScheduler_SchedulerWorkPlace {
            get {
                return ResourceManager.GetString("V_OrderScheduler_SchedulerWorkPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 服務狀態ID 的本地化字符串。
        /// </summary>
        internal static string V_OrderScheduler_ServiceJobStateID {
            get {
                return ResourceManager.GetString("V_OrderScheduler_ServiceJobStateID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 服務狀態 的本地化字符串。
        /// </summary>
        internal static string V_OrderScheduler_ServiceJobStateLabel {
            get {
                return ResourceManager.GetString("V_OrderScheduler_ServiceJobStateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 服務內容ID 的本地化字符串。
        /// </summary>
        internal static string V_OrderScheduler_ServiceNatureID {
            get {
                return ResourceManager.GetString("V_OrderScheduler_ServiceNatureID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 服務內容 的本地化字符串。
        /// </summary>
        internal static string V_OrderScheduler_ServiceNatureLabel {
            get {
                return ResourceManager.GetString("V_OrderScheduler_ServiceNatureLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 服務日期 的本地化字符串。
        /// </summary>
        internal static string V_OrderScheduler_ServiceWorkDate {
            get {
                return ResourceManager.GetString("V_OrderScheduler_ServiceWorkDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 服務地點 的本地化字符串。
        /// </summary>
        internal static string V_OrderScheduler_ServiceWorkPlace {
            get {
                return ResourceManager.GetString("V_OrderScheduler_ServiceWorkPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 服務時間 的本地化字符串。
        /// </summary>
        internal static string V_OrderScheduler_ServiceWorkTime {
            get {
                return ResourceManager.GetString("V_OrderScheduler_ServiceWorkTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 拖輪簡稱 的本地化字符串。
        /// </summary>
        internal static string V_OrderScheduler_SimpleName {
            get {
                return ResourceManager.GetString("V_OrderScheduler_SimpleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分配的拖輪ID 的本地化字符串。
        /// </summary>
        internal static string V_OrderScheduler_TugID {
            get {
                return ResourceManager.GetString("V_OrderScheduler_TugID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 開始工作時間 的本地化字符串。
        /// </summary>
        internal static string V_OrderScheduler_WorkCommencedTime {
            get {
                return ResourceManager.GetString("V_OrderScheduler_WorkCommencedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 完成工作時間 的本地化字符串。
        /// </summary>
        internal static string V_OrderScheduler_WorkCompletedTime {
            get {
                return ResourceManager.GetString("V_OrderScheduler_WorkCompletedTime", resourceCulture);
            }
        }
    }
}
